version: '3.5'
services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: USERRRR
      POSTGRES_PASSWORD: PASSWORDDDDDD
    volumes:
      - 'larissa-postgres-data:/var/lib/postgresql/data'

volumes:
  airbag-postgres-data:
    name: airbag-db
